# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gitgolem}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["PoTa"]
  s.date = %q{2011-05-10}
  s.description = %q{Golem provides an easy way to host and manage access to git repositories on a server under a single user.}
  s.email = %q{pota@mosfet.hu}
  s.executables = ["golem", "golem-shell"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
    "TODO"
  ]
  s.files = [
    ".document",
    ".yardopts",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "bin/golem",
    "bin/golem-shell",
    "lib/gitgolem.rb",
    "lib/golem.rb",
    "lib/golem/access.rb",
    "lib/golem/command.rb",
    "lib/golem/command/auth.rb",
    "lib/golem/command/clear_repositories.rb",
    "lib/golem/command/create_repository.rb",
    "lib/golem/command/delete_repository.rb",
    "lib/golem/command/environment.rb",
    "lib/golem/command/save_config.rb",
    "lib/golem/command/setup_db.rb",
    "lib/golem/command/update_hooks.rb",
    "lib/golem/command/update_keys_file.rb",
    "lib/golem/config.rb",
    "lib/golem/db.rb",
    "lib/golem/db/pg.rb",
    "lib/golem/db/postgres.sql",
    "lib/golem/db/static.rb",
    "lib/golem/parser.rb",
    "lib/golem/version.rb",
    "test/helper.rb",
    "test/test_access.rb",
    "test/test_config.rb",
    "test/test_db.rb"
  ]
  s.homepage = %q{http://github.com/eLod/golem}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{Gem to host git repositories.}
  s.test_files = [
    "test/helper.rb",
    "test/test_access.rb",
    "test/test_config.rb",
    "test/test_db.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<bluecloth>, [">= 0"])
      s.add_development_dependency(%q<test-unit>, ["~> 1"])
    else
      s.add_dependency(%q<yard>, ["~> 0.6.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<bluecloth>, [">= 0"])
      s.add_dependency(%q<test-unit>, ["~> 1"])
    end
  else
    s.add_dependency(%q<yard>, ["~> 0.6.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<bluecloth>, [">= 0"])
    s.add_dependency(%q<test-unit>, ["~> 1"])
  end
end

